### ISSUE TITLE
can not create an interface with register as abstract method

### ISSUE THREAD

**Issue by sscNZ** [aranzgeo/pure_interface#4]
The following fails, causing issues with using register as a method on PureInterface's.  Possible other unavailable methods due to the same bug.

```
from pure_interface import PureInterface, abstractmethod
class Foo(PureInterface):
    @abstractmethod
    def register(self, a, b):
        """"""
```

> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
>   File pure_interface.py, line 273, in __new__
>   File pure_interface.py", line 324, in _check_method_signatures
> InterfaceError: __builtin__.Foo.register argments does not match base class

**Comment by tim-mitchell** [comment]
Fixed.
